QUIZ24-42 Ajuster trame S si temps de qestion = 0
btssn-lasalle-84/quizzy-2024 pull request #35
Opened 2024-05-26 18:24 UTC by ThomasHni

Ajout d’une condition `if`dans `passerQuestionSuivante()` pour terminer la question et passer à la question suivante s’il n’y a pas de temps.

2024-05-26 18:32 UTC, ThomasHni commented on quizzy-desktop/quizzy.cpp
> +    else if(etat == QuestionDemarree && getQuestion()->getDuree() == 0)
J'ai ajouté cette condition, mais le seul problème est que la visualisation des choix n'apparaît pas à l'écran car la question suivante s'affiche(bien qu'ils soient correctement comptabilisés). Les choix sont bien visibles si la dernière question ne comporte elle non plus aucun temps.

2024-05-26 19:15 UTC, tvaira commented on quizzy-desktop/quizzy.cpp
> +    else if(etat == QuestionDemarree && getQuestion()->getDuree() == 0)
Tu ne t'en sortiras pas comment cela.

Tu as deux solutions :

1. Tu affiches les choix quand tu les reçois puisqu'il n'y a pas de durée, ou
2. Vous ajoutez une trame pour le faire genre la trame `$C\n` pour afficher les choix participants avant de recevoir la trame `S`

2024-05-26 19:20 UTC, ThomasHni commented on quizzy-desktop/quizzy.cpp
> +    else if(etat == QuestionDemarree && getQuestion()->getDuree() == 0)
D'accord !

2024-05-27 05:39 UTC, tvaira requested changes

2024-05-27 05:39 UTC, tvaira commented on quizzy-desktop/quizzy.cpp
> +            emit questionTerminee();
Non, ce n'est pas correct car ça n'a pas de signification. Il te faut créer et émettre un nouveau signal `choixParticipant()`. Ensuite, tu connectes ce nouveau signal au slot `afficherChoixParticipants()` de `IHMQuizzy`.

2024-05-27 05:39 UTC, tvaira commented on quizzy-desktop/quizzy.cpp
> +    if(etat == QuestionDemarree && getQuestion()->getDuree() == 0)
Si c'est la dernière question ? Il faut aussi gérer ça pour la trame de fin `F`.

2024-05-27 09:14 UTC, tvaira approved these changes

2024-05-27 09:19 UTC, merged