Adapter l'ihm pour affichage raspberry
btssn-lasalle-84/quizzy-2024 pull request #38
Opened 2024-05-29 13:00 UTC by ThomasHni

Changement du texte `Question n°xx` en `Question x/x`

2024-05-29 19:46 UTC, ThomasHni commented on quizzy-desktop/ihmquizzy.cpp
> +void IHMQuizzy::configurerResponsiveLabels()
A remanier @ThomasHni

2024-05-30 21:42 UTC, ThomasHni commented
Simple question, concernant le remaniement du code. J'ai bien compris que le remaniement du code sert à améliorer la compréhension et la lisibilité du code. 
Du coup, en revoyant mon code, j'ai pensé que les méthodes 
- `placerWidgetsFenetreJeu()`
- et `definirNomsObjets()`
pourraient bénéficier d'un remaniement avec des sous-méthodes, comme par exemple 
- `definirNomsObjetsFenetreXXX()`,
- `placerPropositionABFenetreJeu()`, 
etc.
Qu'en pensez-vous ?

2024-06-01 17:04 UTC, tvaira requested changes

2024-06-01 17:04 UTC, tvaira commented on quizzy-desktop/ihmquizzy.h
> +    QLabel*       labelChronometre;
Il te faut retirer le `labelChronometre`

2024-06-01 17:04 UTC, tvaira commented on quizzy-desktop/ihmquizzy.h
> +    QProgressBar* progressBarChronometre;
Non pas de progressBar dans le nom, tu ne l'as fait pour aucun _widget_ ! Par contre, c'est un compte à rebours !

2024-06-04 17:24 UTC, ThomasHni commented
Petit problème : lorsque je relance un quiz et affiche les résultats, les anciens résultats sont toujours affichés (je me retrouve donc avec les nouveaux résultats affichés par-dessus). La méthode `effacerFenetreResultats` est bien appelée, mais je ne vois pas du tout comment corriger ça 

Voici la méthode effacement :

```cpp
void IHMQuizzy::effacerFenetreResultats()
{
    qDebug() << Q_FUNC_INFO;
    QLayoutItem* child;
    for(int i = layoutPrincipalResultat->count() - 1; i >= 0; --i)
    {
        child = layoutPrincipalResultat->itemAt(i);
        if(child->widget() != titreFenetreResultats)
        {
            delete child->widget();
            delete child;
        }
    }
}
```

2024-06-04 18:39 UTC, tvaira commented
> Petit problème : lorsque je relance un quiz et affiche les résultats, les anciens résultats sont toujours affichés (je me retrouve donc avec les nouveaux résultats affichés par-dessus). La méthode `effacerFenetreResultats` est bien appelée, mais je ne vois pas du tout comment corriger ça
> 
> Voici la méthode d'effacement :
> 
> ```c++
> void IHMQuizzy::effacerFenetreResultats()
> {
>     qDebug() << Q_FUNC_INFO;
>     QLayoutItem* child;
>     for(int i = layoutPrincipalResultat->count() - 1; i >= 0; --i)
>     {
>         child = layoutPrincipalResultat->itemAt(i);
>         if(child->widget() != titreFenetreResultats)
>         {
>             delete child->widget();
>             delete child;
>         }
>     }
> }
> ```
> 
> @tvaira

Tout simplement parce que tu as une structure imbriquée. Prenons un exemple avec deux participants :

```txt
layoutPrincipalResultat
    ->addWidget(titreFenetreResultats)
    ->addLayout(layoutParticipantResultat)
        ->addWidget(nomParticipant)
        ->addWidget(resultatParticipant)
    ->addLayout(layoutParticipantResultat)
        ->addWidget(nomParticipant)
        ->addWidget(resultatParticipant)
```

Donc ton `layoutPrincipalResultat` contient 3 enfants : un _widget_ et deux _layouts_. Et les deux _layouts_ contiennent deux _widgets_.

Tu vois alors que ton code ne "descends" pas d'un niveau pour supprimer les _widgets_ contenus dans les _layouts_ `layoutParticipantResultat`

Pour t'aider :

```cpp
if(child->widget() != nullptr)
    qDebug() << Q_FUNC_INFO << "child est un widget";
if(child->layout() != nullptr)
    qDebug() << Q_FUNC_INFO << "child est un layout";
```

_Petite remarque :_ j'ai une nouvelle fois sauté de joie quand j'ai vu `child`.

2024-06-06 18:39 UTC, tvaira commented
Suite aux demandes, est-ce que tu pourrais : 

- ajouter l'icône _play_ 
- gérer les deux signaux `tabletteConnectee()` et `tabletteDeconnectee()`

2024-06-06 21:13 UTC, ThomasHni commented
Je n'arrive pas du tout à placer le `play_rouge`.

2024-06-07 08:13 UTC, tvaira approved these changes

2024-06-07 08:14 UTC, merged